files:
  include: 'app/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 1
  hex-length: short
  hex-notation: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedbem
  leading-zero: 1
  mixin-name-format: 1
  mixins-before-declarations: 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-literals: 1
  no-disallowed-properties:
    - 1
    - properties:
      - float
  no-duplicate-properties: 1
  no-extends: 1
  no-ids: 1
  no-qualifying-elements: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: alphabetical
  quotes:
    - 1
    - style: double
  variable-name-format: 1
